apiVersion: v1
kind: Service
metadata:
  name: nodeport
  namespace: cicd-space
  labels:
    app: cicd
spec:
  type: NodePort
  selector:
    app: cicd
  ports:
    - port: 3000
      targetPort: 8080
      nodePort: 30012
